[[headers]]
  for = "/.well-known/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

# convenience redirects

[[redirects]]   
  from = "/donate"
  to = "/membership"
  
[[redirects]] 
  from = "/facebook"
  to = "https://www.facebook.com/Hackerspace-Pomorze-103254931521373/"
  
[[redirects]]   
  from = "/twitter"
  to = "https://twitter.com/hspsh"
  
[[redirects]]   
  from = "/github"
  to = "https://github.com/hspsh"

[[redirects]]
  from = "/workadventure"
  to = "https://play.workadventu.re/_/global/hspsh.github.io/hspVenture/map.json"
  
[[redirects]]
  from = "/jitsi"
  to = "https://meet.jit.si/hsp.sh"

[[redirects]]
  from = "/forum"
  to = "https://forum.hsp.sh"

[[redirects]]
  from = "/slack"
  to = "https://forum.hsp.sh/t/zmiana-komunikatora/421"
 
[[redirects]]
  from = "/discord"
  to = "https://discord.gg/2VZfQVejVP"

[[redirects]]   
  from = "/calendar.ics"
  to = "https://calendar.google.com/calendar/ical/c_53083e3ce3f93991ba8f1925ebf30dcdb08b2fd025b9e6a6572d6662a1b523fe%40group.calendar.google.com/public/basic.ics"

[[redirects]]
  from = "/walne_zebranie_czlonkow"
  to = "https://forum.hsp.sh/t/walne-zebranie-czlonkow-05-03-2022/587"

[[redirects]]
  from = "/statut"
  to = "/assets/statut/Statut_HSP_05-03-2022.pdf"

# legacy stuff

[[redirects]]   
  from = "/events/*"
  to = "/posts"

[[redirects]]   
  from = "/posts"
  to = "/blog"

[[redirects]]   
  from = "/partners"
  to = "/membership"

[[redirects]]   
  from = "/join"
  to = "/"

[[redirects]]
  from = "/2021/post-pandemic-reboot/"
  to = "/blog/2021-06-09-post-pandemic-reboot/"

[[redirects]]
  from = "/2020/hs-pomorze/"
  to = "/blog/2020-10-09-hs-pomorze/"
